### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hiornso** [hiornso/csa#1]
_Tasks marked >>> are priorities._

**Manual/Docs:**
- [ ] (#14) make a proper manual
  - [ ] add manual to help tab
- [ ] (#15) make CSA Lua API docs
  - [ ] add docs to Help tab

**Features:**
- [ ] further compression of resources in executable (lrzip?)
- [ ] make tabs pop-outable
- [ ] (#5) change tab when undo/redo in different tab
- [ ] (#6) save/open
- [ ] (#7) add popup to ask for confirmation when a large number of windows would be opened
- [ ] look into adding popup for when window creation fails (preferably without spoofing `error_popup` since that creates a `GtkMessage` advising against creating popups without transient parents?)
- [ ] add button/keybind to close map without closing window? needs to call `free_tracker` and `FREE_STATELIST` on corresponding entries in `Omni` struct (see `free_window_data`) as well as make `captain_map_ui_box` and `captain_map_builtin_button_grid` insensitive. Also, clear map labels and refresh window title.
- [x] >>> (#8) make it so that maps opened via Open From File option or via command line have more informative information such as path/map name in the `ComboBoxText` dropdown - especially for when it's via the command line as currently it's just blank
- [x] >>> (#9) make window titles reflect window states (names of loaded maps in brackets)?
- [ ] >>> Make First Mate and Engineering screens constructed from Lua, so that they can be modded (have file paths be provided by lua, just use `resource://` with paths to compiled-in images to allow base maps to be bundled)
- [ ] Add proper settings integration (`GSettings`?) to allow persistence of settings such as
  - [ ] screen resolution/fullscreen or not when last closed (is this normal behaviour on macos?)
  - [ ] accessibility profile
  - [ ] other preferences
- [ ] Make map opening all be done via File>Open, or File>Open Built-in for built-in maps (replace dropdown with label, map is global across window rather than per-tab)
- [ ] Fix `GtkLevelBar` CSS weirdness
- [ ] Make healthbars controlled via Lua, using Engineering and Tracker inputs (remove +/- buttons?) / generally auto-decrement health when relevant
- [ ] Add undo/redo status in middle space at bottom of window? Or in Edit>Undo/Edit>Redo menus?

**Maps and map features:**
- [ ] (#10) sprite display via lua request
- [ ] (#11) mine tracking (in lua, **needs sprite display**)
- [ ] (#12) finish programming included maps (**needs sprite display**)
- [ ] make safe table access - always check if table before access, use raw functions if reliable access state is required?
- [ ] allow lua to define keys in user_input table?
- [ ] improve rendering performance by adding option to render using GPU (OpenGL... or even Vulkan? probably OpenGL)
- [ ] >> (#4) Add options/functionality to allow the render of the map to be exported as png (easy using cairo) at an arbitrary resolution - should just be create a surface and artificially call draw on it
- [x] >>> Course plotter
- [ ] >>> #3

**Integration:**
- [ ] macos integration for opening files?
- [ ] look into moving macos window control buttons for better integrated appearance, so that there is not a separate header bar for them (in modern macos apps they are integrated into the window rather than being part of a distinct bar)
- [ ] look into adding menu button instead of using menubar on gnome for better integrated appearance
- [ ] >>> (#13) add keyboard shortcuts window (ui file?)
- [ ] look into adding separate recent files option in the File menu - GtkRecentManager?
  - [ ] look into doing with system APIs on macos for proper integration with dock etc

**Icons:**
- [ ] (#2) create dedicated icons for the engineer screen for
   - [ ] mine
   - [ ] special weapon
- [ ] make macos app bundle icon the proper CSA icon (currently it is just a placeholder, and is the App Store icon, since creaing the icon in the special file format macos wants is a pain)

**Git:**
- [x] make the VCL dependency be a proper submodule rather than just being included as a zip file.
